# Generated by Django 4.2 on 2026-09-20 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("venta", "0004_venta_tipo_venta"),
        ("tienda", "0018_plansuscripcion_limite_productos"),
        ("pedidos", "0007_pedido_venta_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuiaRemision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serie", models.CharField(default="T001", max_length=4)),
                ("correlativo", models.CharField(max_length=8)),
                ("numero_guia", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "fecha_emision",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "observacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emisor_ubigeo",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                (
                    "emisor_departamento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "emisor_provincia",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "emisor_distrito",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("emisor_direccion", models.TextField(blank=True, null=True)),
                (
                    "emisor_nombre_comercial",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("dest_tipo_doc", models.CharField(default="6", max_length=2)),
                ("dest_num_doc", models.CharField(max_length=15)),
                ("dest_nombre", models.CharField(max_length=255)),
                (
                    "dest_direccion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tercero_tipo_doc",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "tercero_num_doc",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "tercero_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "comprador_tipo_doc",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "comprador_num_doc",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "comprador_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mod_traslado",
                    models.CharField(
                        choices=[
                            ("01", "Transporte público"),
                            ("02", "Transporte privado"),
                        ],
                        default="02",
                        max_length=2,
                    ),
                ),
                ("cod_traslado", models.CharField(default="01", max_length=2)),
                ("des_traslado", models.CharField(default="VENTA", max_length=100)),
                ("fec_traslado", models.DateField()),
                ("peso_total", models.DecimalField(decimal_places=3, max_digits=12)),
                ("und_peso_total", models.CharField(default="KGM", max_length=3)),
                (
                    "peso_items",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "sustento_peso",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("num_bultos", models.PositiveIntegerField(blank=True, null=True)),
                ("partida_ubigeo", models.CharField(max_length=6)),
                ("partida_direccion", models.CharField(max_length=255)),
                (
                    "partida_cod_local",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("partida_ruc", models.CharField(blank=True, max_length=11, null=True)),
                ("llegada_ubigeo", models.CharField(max_length=6)),
                ("llegada_direccion", models.CharField(max_length=255)),
                (
                    "llegada_cod_local",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("llegada_ruc", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "transportista_tipo_doc",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "transportista_num_doc",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "transportista_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transportista_nro_mtc",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("vehiculo_placa", models.CharField(max_length=20)),
                (
                    "vehiculo_nro_circulacion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "vehiculo_nro_autorizacion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "vehiculo_cod_emisor",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("vehiculo_secundarios", models.JSONField(blank=True, default=list)),
                ("indicadores", models.JSONField(blank=True, default=list)),
                ("contenedores", models.JSONField(blank=True, default=list)),
                ("logo_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADO", "Enviado"),
                            ("ACEPTADO", "Aceptado"),
                            ("RECHAZADO", "Rechazado"),
                            ("ERROR", "Error"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                (
                    "estado_sunat",
                    models.CharField(
                        blank=True, default="PENDIENTE", max_length=50, null=True
                    ),
                ),
                ("ambiente", models.CharField(blank=True, max_length=20, null=True)),
                ("xml_url", models.URLField(blank=True, max_length=500, null=True)),
                ("pdf_url", models.URLField(blank=True, max_length=500, null=True)),
                ("cdr_url", models.URLField(blank=True, max_length=500, null=True)),
                ("payload_enviado", models.JSONField(blank=True, default=dict)),
                (
                    "respuesta_sunat",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guias_remision",
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "tienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guias_remision",
                        to="tienda.tienda",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guias_remision",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guias_remision",
                        to="venta.venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guía de Remisión",
                "verbose_name_plural": "Guías de Remisión",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="GuiaRemisionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=255)),
                ("unidad", models.CharField(default="NIU", max_length=10)),
                ("cantidad", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "cod_prod_sunat",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("atributos", models.JSONField(blank=True, default=list)),
                (
                    "guia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="guia_remision.guiaremision",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="GuiaRemisionConductor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Principal", "Principal"),
                            ("Secundario", "Secundario"),
                        ],
                        default="Principal",
                        max_length=20,
                    ),
                ),
                ("tipo_doc", models.CharField(default="01", max_length=2)),
                ("nro_doc", models.CharField(max_length=15)),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("licencia", models.CharField(max_length=20)),
                (
                    "guia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conductores",
                        to="guia_remision.guiaremision",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="GuiaDocumentoRelacionado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_desc", models.CharField(default="Factura", max_length=50)),
                ("tipo", models.CharField(max_length=2)),
                ("nro", models.CharField(max_length=30)),
                ("emisor", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "guia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docs_relacionados",
                        to="guia_remision.guiaremision",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="guiaremision",
            constraint=models.UniqueConstraint(
                fields=("tienda", "serie", "correlativo"),
                name="uq_guia_tienda_serie_correlativo",
            ),
        ),
    ]
