# Generated by Django 4.2 on 2026-09-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guia_remision", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guiaremisionconductor",
            name="tipo_doc",
            field=models.CharField(default="1", max_length=2),
        ),
    ]
