# Generated by Django 4.2 on 2026-06-21 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0001_initial'),
        ('tienda', '0004_alter_tienda_correlativo_inicial_boleta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('fecha_realizacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('metodo_pago', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(choices=[('COTIZADO', 'Cotizado'), ('PENDIENTE', 'Pendiente'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='COTIZADO', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('gravado_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('igv_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('productos_json', models.JSONField(blank=True, default=list)),
                ('descuento_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('tipo_documento_cliente', models.CharField(max_length=2, null=True)),
                ('numero_documento_cliente', models.CharField(max_length=15, null=True)),
                ('nombre_cliente', models.CharField(max_length=255, null=True)),
                ('email_cliente', models.EmailField(max_length=255, null=True)),
                ('telefono_cliente', models.EmailField(max_length=255, null=True)),
                ('direccion_cliente', models.EmailField(max_length=255, null=True)),
                ('numero_pedido', models.CharField(max_length=50, unique=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.tienda')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('stock_disponible', models.BooleanField(default=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_igv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_igv', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_afectacion_igv', models.CharField(max_length=10)),
                ('total_impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_original', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
