# Generated by Django 4.2 on 2026-08-24 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tienda", "0004_alter_tienda_correlativo_inicial_boleta_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("producto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_pedido", models.CharField(max_length=50, unique=True)),
                (
                    "tipo_pedido",
                    models.CharField(
                        choices=[
                            ("MESA", "Mesa"),
                            ("DELIVERY", "Delivery"),
                            ("TAKEAWAY", "Takeaway"),
                            ("MOSTRADOR", "Mostrador"),
                        ],
                        default="MOSTRADOR",
                        max_length=20,
                    ),
                ),
                (
                    "canal_venta",
                    models.CharField(
                        choices=[
                            ("PRESENCIAL", "Presencial"),
                            ("WHATSAPP", "WhatsApp"),
                            ("WEB", "Web"),
                            ("TELEFONO", "Teléfono"),
                        ],
                        default="PRESENCIAL",
                        max_length=20,
                    ),
                ),
                ("fecha_hora", models.DateTimeField()),
                (
                    "fecha_realizacion",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("fecha_vencimiento", models.DateTimeField(blank=True, null=True)),
                ("fecha_entrega_estimada", models.DateTimeField(blank=True, null=True)),
                ("fecha_cancelacion", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("COTIZADO", "Cotizado"),
                            ("PENDIENTE", "Pendiente"),
                            ("CONFIRMADO", "Confirmado"),
                            ("EN_PREPARACION", "En preparación"),
                            ("LISTO", "Listo"),
                            ("ENTREGADO", "Entregado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="COTIZADO",
                        max_length=20,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[("NORMAL", "Normal"), ("URGENTE", "Urgente")],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "metodo_pago",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "gravado_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "igv_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "descuento_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "costo_envio",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "estado_pago",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PARCIAL", "Parcial"),
                            ("PAGADO", "Pagado"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                (
                    "monto_adelanto",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "metodo_pago_adelanto",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tipo_documento_cliente",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "numero_documento_cliente",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "nombre_cliente",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_cliente",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "telefono_cliente",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("direccion_envio", models.TextField(blank=True, null=True)),
                (
                    "referencia_ubicacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("notas_internas", models.TextField(blank=True, null=True)),
                ("motivo_cancelacion", models.TextField(blank=True, null=True)),
                (
                    "referencia_externa",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("productos_json", models.JSONField(blank=True, default=list)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "tienda",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tienda.tienda",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="PedidoProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("stock_disponible", models.BooleanField(default=True)),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("valor_venta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("base_igv", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "porcentaje_igv",
                    models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
                ),
                ("igv", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tipo_afectacion_igv", models.CharField(max_length=10)),
                (
                    "total_impuestos",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "costo_original",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pedidos.pedido"
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="producto.producto",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
    ]
