# Generated by Django 4.2 on 2026-08-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="canal_venta",
            field=models.CharField(
                choices=[
                    ("PRESENCIAL", "Presencial"),
                    ("WHATSAPP", "WhatsApp"),
                    ("WEB", "Web"),
                    ("TELEFONO", "Teléfono"),
                    ("TIKTOK", "TikTok"),
                ],
                default="PRESENCIAL",
                max_length=20,
            ),
        ),
    ]
