# Generated by Django 4.2 on 2026-09-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_alter_pedido_canal_venta"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="productos_pedido_json",
            field=models.TextField(blank=True, default=""),
        ),
    ]
