# Generated by Django 4.2 on 2026-09-20 01:21

from django.db import migrations, models


def mapear_estados_antiguos(apps, schema_editor):
    Pedido = apps.get_model("pedidos", "Pedido")
    # Todo lo no final pasa a PENDIENTE, ENTREGADO pasa a COMPLETADO
    Pedido.objects.filter(
        estado__in=["COTIZADO", "CONFIRMADO", "EN_PREPARACION", "LISTO"]
    ).update(estado="PENDIENTE")
    Pedido.objects.filter(estado="ENTREGADO").update(estado="COMPLETADO")


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0003_pedido_productos_pedido_json"),
    ]

    operations = [
        migrations.RunPython(mapear_estados_antiguos, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("COMPLETADO", "Completado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
    ]
