# Generated by Django 4.2 on 2026-09-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0004_simplificar_estados_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="plus_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
