# Generated by Django 4.2 on 2026-09-20 02:48

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def backfill_vencimiento(apps, schema_editor):
    Pedido = apps.get_model("pedidos", "Pedido")
    ahora = timezone.now()
    for pedido in Pedido.objects.filter(fecha_vencimiento__isnull=True):
        base = pedido.fecha_hora or pedido.date_created or ahora
        if timezone.is_naive(base):
            base = timezone.make_aware(base)
        pedido.fecha_vencimiento = base + timedelta(days=30)
        pedido.fecha_eliminacion = pedido.fecha_vencimiento + timedelta(days=3)
        if pedido.estado == "PENDIENTE" and pedido.fecha_vencimiento <= ahora:
            pedido.estado = "VENCIDO"
        pedido.save(update_fields=["fecha_vencimiento", "fecha_eliminacion", "estado"])


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0005_pedido_plus_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="fecha_eliminacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("COMPLETADO", "Completado"),
                    ("CANCELADO", "Cancelado"),
                    ("VENCIDO", "Vencido"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_vencimiento, reverse_code=migrations.RunPython.noop),
    ]
