# Generated by Django 4.2 on 2026-09-20 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0004_venta_tipo_venta"),
        ("pedidos", "0006_pedido_vencimiento_eliminacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to="venta.venta",
            ),
        ),
    ]
