# Generated by Django 4.2 on 2025-03-18 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_remove_producto_precio_producto_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
    ]
