# Generated by Django 4.2 on 2025-04-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_remove_producto_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria_nombre',
        ),
    ]
