# Generated by Django 4.2 on 2025-08-18 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_tienda_activo_alter_tienda_capacidad_and_more'),
        ('producto', '0004_remove_producto_categoria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.tienda'),
        ),
    ]
