# Generated by Django 4.2 on 2025-11-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='productos/default.jpg', null=True, upload_to='productos/'),
        ),
    ]
