# Generated by Django 4.2 on 2025-11-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_alter_producto_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='https://sublimac.com/wp-content/uploads/2017/11/default-placeholder.png', null=True, upload_to='productos/'),
        ),
    ]
