# Generated by Django 4.2 on 2025-11-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0010_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='productos/'),
        ),
    ]
