# Generated by Django 4.2 on 2026-06-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_remove_proveedor_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
