# Generated by Django 4.2 on 2025-08-18 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_tienda_activo_alter_tienda_capacidad_and_more'),
        ('proveedor', '0002_alter_proveedor_contacto_alter_proveedor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='tienda.tienda'),
        ),
    ]
