# Generated by Django 4.2 on 2025-08-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_caja_fecha_cancelacion_caja_fecha_reinicio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='operacioncaja',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='caja',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='operacioncaja',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
