# Generated by Django 4.2 on 2026-01-15 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('photo_url', models.CharField(default='https://res.cloudinary.com/ddksrkond/image/upload/v1688411778/default_dfvymc.webp', max_length=255)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('es_empleado', models.BooleanField(default=False)),
                ('desactivate_account', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_tienda', to='tienda.tienda')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_created'],
                'permissions': [('can_make_sale', 'Puede hacer una venta'), ('can_cancel_sale', 'Puede cancelar una venta'), ('can_create_inventory', 'Puede crear inventario'), ('can_modify_inventory', 'Puede modificar inventario'), ('can_update_inventory', 'Puede actualizar inventario'), ('can_delete_inventory', 'Puede eliminar inventario'), ('can_create_product', 'Puede crear un producto'), ('can_update_product', 'Puede actualizar un producto'), ('can_delete_product', 'Puede eliminar un producto'), ('can_create_category', 'Puede crear una categoría'), ('can_modify_category', 'Puede modificar una categoría'), ('can_delete_category', 'Puede eliminar una categoría'), ('can_create_supplier', 'Puede crear proveedores'), ('can_modify_supplier', 'Puede modificar proveedores'), ('can_delete_supplier', 'Puede eliminar proveedores'), ('can_create_store', 'Puede crear una tienda'), ('can_modify_store', 'Puede modificar una tienda'), ('can_delete_store', 'Puede eliminar una tienda'), ('view_sale', 'Puede ver las ventas'), ('view_inventory', 'Puede ver el inventario'), ('view_product', 'Puede ver los productos'), ('view_category', 'Puede ver las categorías'), ('view_supplier', 'Puede ver los proveedores'), ('view_store', 'Puede ver las tiendas'), ('can_create_user', 'Puede crear nuevos usuarios'), ('can_create_proveedor', 'Puede crear un proveedor'), ('can_update_proveedor', 'Puede actualizar un proveedor'), ('can_delete_proveedor', 'Puede eliminar un proveedor')],
            },
        ),
    ]
