# Generated by Django 4.2 on 2026-08-29 15:05

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="modulos_habilitados",
            field=models.JSONField(
                blank=True,                 default=apps.user.models.default_modulos_habilitados,
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="navbar_type",
            field=models.CharField(
                choices=[("top", "Top"), ("normal", "Normal")],
                default="top",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="light",
                max_length=10,
            ),
        ),
    ]
