# Generated by Django 4.2 on 2026-08-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_useraccount_modulos_habilitados_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
