# Generated by Django 5.1.2 on 2025-02-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_nickname_useraccount_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='es_empleado',
            field=models.BooleanField(default=False),
        ),
    ]
