# Generated by Django 4.2 on 2025-03-19 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useraccount_es_empleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'permissions': [('can_make_sale', 'Puede hacer una venta'), ('can_cancel_sale', 'Puede cancelar una venta'), ('can_create_inventory', 'Puede crear inventario'), ('can_modify_inventory', 'Puede modificar inventario'), ('can_update_inventory', 'Puede actualizar inventario'), ('can_delete_inventory', 'Puede eliminar inventario'), ('can_create_product', 'Puede crear un producto'), ('can_update_product', 'Puede actualizar un producto'), ('can_delete_product', 'Puede eliminar un producto'), ('can_create_category', 'Puede crear una categoría'), ('can_modify_category', 'Puede modificar una categoría'), ('can_delete_category', 'Puede eliminar una categoría'), ('can_create_supplier', 'Puede crear proveedores'), ('can_modify_supplier', 'Puede modificar proveedores'), ('can_delete_supplier', 'Puede eliminar proveedores'), ('can_create_store', 'Puede crear una tienda'), ('can_modify_store', 'Puede modificar una tienda'), ('can_delete_store', 'Puede eliminar una tienda'), ('view_sale', 'Puede ver las ventas'), ('view_inventory', 'Puede ver el inventario'), ('view_product', 'Puede ver los productos'), ('view_category', 'Puede ver las categorías'), ('view_supplier', 'Puede ver los proveedores'), ('view_store', 'Puede ver las tiendas')]},
        ),
    ]
