# Generated by Django 4.2 on 2026-09-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_useraccount_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="cert_clave_privada",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="cert_clave_publica",
            field=models.TextField(blank=True, null=True),
        ),
    ]
