# Generated by Django 4.2 on 2026-09-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_useraccount_cert_clave_privada_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="cert_clave_privada",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="cert_clave_publica",
        ),
    ]
