# Generated by Django 4.2 on 2025-08-18 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_tienda_encargado'),
        ('user', '0004_alter_useraccount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'permissions': [('can_make_sale', 'Puede hacer una venta'), ('can_cancel_sale', 'Puede cancelar una venta'), ('can_create_inventory', 'Puede crear inventario'), ('can_modify_inventory', 'Puede modificar inventario'), ('can_update_inventory', 'Puede actualizar inventario'), ('can_delete_inventory', 'Puede eliminar inventario'), ('can_create_product', 'Puede crear un producto'), ('can_update_product', 'Puede actualizar un producto'), ('can_delete_product', 'Puede eliminar un producto'), ('can_create_category', 'Puede crear una categoría'), ('can_modify_category', 'Puede modificar una categoría'), ('can_delete_category', 'Puede eliminar una categoría'), ('can_create_supplier', 'Puede crear proveedores'), ('can_modify_supplier', 'Puede modificar proveedores'), ('can_delete_supplier', 'Puede eliminar proveedores'), ('can_create_store', 'Puede crear una tienda'), ('can_modify_store', 'Puede modificar una tienda'), ('can_delete_store', 'Puede eliminar una tienda'), ('view_sale', 'Puede ver las ventas'), ('view_inventory', 'Puede ver el inventario'), ('view_product', 'Puede ver los productos'), ('view_category', 'Puede ver las categorías'), ('view_supplier', 'Puede ver los proveedores'), ('view_store', 'Puede ver las tiendas'), ('can_create_user', 'Puede crear nuevos usuarios')]},
        ),
        migrations.AddField(
            model_name='useraccount',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_tienda', to='tienda.tienda'),
        ),
    ]
