# Generated by Django 4.2 on 2025-08-25 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_tienda_encargado'),
        ('user', '0005_alter_useraccount_options_useraccount_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_tienda', to='tienda.tienda'),
        ),
    ]
