# Generated by Django 4.2 on 2026-01-15 02:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(max_length=10)),
                ('serie', models.CharField(max_length=4, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('correlativo', models.CharField(max_length=8, null=True)),
                ('moneda', models.CharField(max_length=10, null=True)),
                ('gravadas', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('valorVenta', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('leyenda', models.TextField(blank=True, null=True)),
                ('tipo_documento_cliente', models.CharField(max_length=2, null=True)),
                ('numero_documento_cliente', models.CharField(max_length=15, null=True)),
                ('nombre_cliente', models.CharField(max_length=255, null=True)),
                ('xml_firmado', models.TextField(blank=True, null=True)),
                ('codigo_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('cdr_respuesta', models.TextField(blank=True, null=True)),
                ('estado_sunat', models.CharField(default='Pendiente', max_length=50, null=True)),
                ('xml_url', models.URLField(blank=True, max_length=500, null=True)),
                ('pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cdr_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ticket_url', models.URLField(blank=True, max_length=500, null=True)),
                ('items', models.JSONField(default=list)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('descuento_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='NotaCreditoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=10)),
                ('correlativo', models.CharField(max_length=8)),
                ('tipo_comprobante_modifica', models.CharField(choices=[('01', 'Factura electrónica'), ('03', 'Boleta de venta electrónica')], help_text='Tipo de comprobante que se modifica', max_length=2)),
                ('serie_modifica', models.CharField(max_length=10)),
                ('correlativo_modifica', models.CharField(max_length=8)),
                ('tipo_motivo', models.CharField(choices=[('01', 'Anulación de la operación'), ('02', 'Anulación por error en el RUC'), ('03', 'Corrección por error en la descripción'), ('04', 'Descuento global'), ('05', 'Descuento por ítem'), ('06', 'Devolución total'), ('07', 'Devolución por ítem')], help_text='Código de motivo según catálogo SUNAT', max_length=2)),
                ('motivo', models.CharField(help_text='Descripción del motivo', max_length=255)),
                ('moneda', models.CharField(default='PEN', max_length=3)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estado_sunat', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('Error', 'Error')], default='Pendiente', max_length=20)),
                ('xml_url', models.URLField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('cdr_url', models.URLField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('comprobante_modificado', models.ForeignKey(help_text='Comprobante electrónico original (factura o boleta) que se modifica', on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='comprobante.comprobanteelectronico')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
