# Generated by Django 5.1.2 on 2025-02-09 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("venta", "0002_rename_fecha_venta_venta_fecha_hora_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComprobanteElectronico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_comprobante",
                    models.CharField(
                        choices=[
                            ("BOLETA", "Boleta Electrónica"),
                            ("FACTURA", "Factura Electrónica"),
                        ],
                        max_length=10,
                    ),
                ),
                ("serie", models.CharField(max_length=4)),
                ("numero", models.CharField(max_length=8)),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                ("xml_firmado", models.TextField(blank=True, null=True)),
                (
                    "codigo_hash",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cdr_respuesta", models.TextField(blank=True, null=True)),
                ("estado_sunat", models.CharField(default="Pendiente", max_length=50)),
                (
                    "venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comprobante",
                        to="venta.venta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serie", models.CharField(max_length=4)),
                ("numero", models.CharField(max_length=8)),
                ("motivo", models.TextField()),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                ("xml_firmado", models.TextField(blank=True, null=True)),
                ("cdr_respuesta", models.TextField(blank=True, null=True)),
                ("estado_sunat", models.CharField(default="Pendiente", max_length=50)),
                (
                    "comprobante_original",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nota_credito",
                        to="comprobante.comprobanteelectronico",
                    ),
                ),
            ],
        ),
    ]
