# Generated by Django 4.2 on 2026-01-15 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comprobante', '0001_initial'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacreditodb',
            name='venta',
            field=models.OneToOneField(help_text='Venta original a la que se aplica la nota de crédito', on_delete=django.db.models.deletion.CASCADE, related_name='nota_credito', to='venta.venta'),
        ),
        migrations.AddField(
            model_name='comprobanteelectronico',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='venta.venta'),
        ),
    ]
