# Generated by Django 5.1.2 on 2025-02-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comprobante", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comprobanteelectronico",
            name="estado_sunat",
            field=models.CharField(default="Pendiente", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="comprobanteelectronico",
            name="numero",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="comprobanteelectronico",
            name="serie",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
