# Generated by Django 4.2 on 2026-01-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteelectronico',
            name='estado_sunat',
            field=models.CharField(default='PENDIENTE', max_length=50, null=True),
        ),
    ]
