# Generated by Django 5.1.2 on 2025-02-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comprobante", "0002_alter_comprobanteelectronico_estado_sunat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="cdr_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="direccion_cliente",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="email_cliente",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="gravadas",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="igv",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="leyenda",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="nombre_cliente",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="numero_documento_cliente",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="pdf_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="sub_total",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="telefono_cliente",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="ticket_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="tipo_documento_cliente",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="valor_venta",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="xml_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="comprobanteelectronico",
            name="numero",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
