# Generated by Django 4.2 on 2026-09-01 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0003_add_cliente_json"),
        ("comprobante", "0003_alter_comprobanteelectronico_estado_sunat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comprobanteelectronico",
            name="venta",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comprobante",
                to="venta.venta",
            ),
        ),
    ]
