# Generated by Django 4.2 on 2025-03-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante', '0004_rename_valor_venta_comprobanteelectronico_valorventa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteelectronico',
            name='correlativo',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='comprobanteelectronico',
            name='tipo_comprobante',
            field=models.CharField(max_length=10),
        ),
    ]
