# Generated by Django 4.2 on 2025-08-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante', '0005_alter_comprobanteelectronico_correlativo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprobanteelectronico',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='notacredito',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='comprobanteelectronico',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
