# Generated by Django 4.2 on 2025-10-07 03:07

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_alter_venta_options_alter_ventaproducto_options_and_more'),
        ('comprobante', '0006_alter_comprobanteelectronico_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCreditoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=10)),
                ('correlativo', models.CharField(max_length=8)),
                ('tipo_comprobante_modifica', models.CharField(choices=[('01', 'Factura electrónica'), ('03', 'Boleta de venta electrónica')], help_text='Tipo de comprobante que se modifica', max_length=2)),
                ('serie_modifica', models.CharField(max_length=10)),
                ('correlativo_modifica', models.CharField(max_length=8)),
                ('tipo_motivo', models.CharField(choices=[('01', 'Anulación de la operación'), ('02', 'Anulación por error en el RUC'), ('03', 'Corrección por error en la descripción'), ('04', 'Descuento global'), ('05', 'Descuento por ítem'), ('06', 'Devolución total'), ('07', 'Devolución por ítem')], help_text='Código de motivo según catálogo SUNAT', max_length=2)),
                ('motivo', models.CharField(help_text='Descripción del motivo', max_length=255)),
                ('moneda', models.CharField(default='PEN', max_length=3)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estado_sunat', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('Error', 'Error')], default='Pendiente', max_length=20)),
                ('xml_url', models.URLField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('cdr_url', models.URLField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('comprobante_modificado', models.ForeignKey(help_text='Comprobante electrónico original (factura o boleta) que se modifica', on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='comprobante.comprobanteelectronico')),
                ('venta', models.OneToOneField(help_text='Venta original a la que se aplica la nota de crédito', on_delete=django.db.models.deletion.CASCADE, related_name='nota_credito', to='venta.venta')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.DeleteModel(
            name='NotaCredito',
        ),
    ]
