# Generated by Django 4.2 on 2025-11-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante', '0007_notacreditodb_delete_notacredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteelectronico',
            name='descuento_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
