# Generated by Django 4.2 on 2025-08-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_inventario_costo_compra_inventario_costo_docena_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='inventario',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
