# Generated by Django 4.2 on 2025-11-15 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_inventario_options_inventario_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='proveedor',
        ),
    ]
