# Generated by Django 4.2 on 2026-06-21 17:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
        ('tienda', '0004_alter_tienda_correlativo_inicial_boleta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('01', 'Factura'), ('03', 'Boleta')], max_length=2)),
                ('serie', models.CharField(max_length=10)),
                ('correlativo', models.CharField(max_length=20)),
                ('fecha_emision', models.DateField()),
                ('moneda', models.CharField(default='PEN', max_length=10)),
                ('gravadas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo_documento_proveedor', models.CharField(max_length=2, null=True)),
                ('numero_documento_proveedor', models.CharField(max_length=15, null=True)),
                ('nombre_proveedor', models.CharField(max_length=255, null=True)),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='compras/xml/', validators=[django.core.validators.FileExtensionValidator(['xml'])])),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='compras/pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('items', models.JSONField(blank=True, default=list)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedor.proveedor')),
                ('tienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.tienda')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
