# Generated by Django 4.2 on 2026-01-15 02:32

import apps.compras.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('01', 'Factura'), ('03', 'Boleta'), ('04', 'Nota de Crédito')], max_length=2)),
                ('serie', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to=apps.compras.models.Compra.archivo_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to=apps.compras.models.Compra.archivo_upload_path, validators=[django.core.validators.FileExtensionValidator(['xml'])])),
                ('archivo_txt', models.FileField(blank=True, null=True, upload_to='compras/txt/', validators=[django.core.validators.FileExtensionValidator(['txt'])])),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedor.proveedor')),
            ],
        ),
    ]
