# Generated by Django 4.2 on 2026-06-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantecompra',
            name='dctos_totales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='comprobantecompra',
            name='documento_relacionado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='comprobantecompra',
            name='enlace_verificacion',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='comprobantecompra',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobantecompra',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comprobantecompra',
            name='icbper',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='comprobantecompra',
            name='op_exoneradas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='comprobantecompra',
            name='op_gratuitas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='comprobantecompra',
            name='op_inafectas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comprobantecompra',
            name='nombre_proveedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comprobantecompra',
            name='numero_documento_proveedor',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='comprobantecompra',
            name='tipo_documento_proveedor',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddConstraint(
            model_name='comprobantecompra',
            constraint=models.UniqueConstraint(fields=('proveedor', 'tipo_comprobante', 'serie', 'correlativo'), name='unique_comprobante_por_proveedor'),
        ),
    ]
