# Generated by Django 4.2 on 2026-08-23 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0004_alter_tienda_correlativo_inicial_boleta_and_more"),
        ("compras", "0002_comprobantecompra_dctos_totales_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "tienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tienda.tienda"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
    ]
