# Generated by Django 4.2 on 2026-08-27 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0003_compra"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compra",
            name="tienda",
        ),
        migrations.RemoveConstraint(
            model_name="comprobantecompra",
            name="unique_comprobante_por_proveedor",
        ),
        migrations.DeleteModel(
            name="Compra",
        ),
    ]
