# Generated by Django 4.2 on 2026-09-04 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0012_alter_tienda_tipo_style_boleta_ticket"),
        ("compras", "0004_remove_compra_tienda_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComprobanteCompraFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("xml_url", models.URLField(blank=True, max_length=300, null=True)),
                ("pdf_url", models.URLField(blank=True, max_length=300, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "tienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tienda.tienda"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
    ]
