# Generated by Django 4.2 on 2026-09-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0005_comprobantecomprafiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobantecomprafiles",
            name="tipo_comprobante",
            field=models.CharField(
                choices=[("01", "Factura"), ("03", "Boleta")],
                default="01",
                max_length=2,
            ),
        ),
    ]
