# Generated by Django 4.2 on 2026-09-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0006_comprobantecomprafiles_tipo_comprobante"),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobantecompra",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="comprobantecompra",
            name="pdf_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="comprobantecompra",
            name="xml_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name="ComprobanteCompraFiles",
        ),
    ]
