# Generated by Django 4.2 on 2026-09-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0007_comprobantecompra_image_url_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="comprobantecompra",
            constraint=models.UniqueConstraint(
                fields=("tienda", "tipo_comprobante", "serie", "correlativo"),
                name="uq_compra_tienda_tipo_serie_corr",
            ),
        ),
    ]
