# Generated by Django 4.2 on 2026-01-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='document',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('document', 'tienda'), name='unique_document_by_tienda'),
        ),
    ]
