# Generated by Django 5.1.2 on 2025-02-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cliente",
            old_name="fecha_nacimiento",
            new_name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="activo",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="apellido",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="codigo_postal",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="direccion",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="dni",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="email",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="fecha_registro",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="genero",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="pais",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="telefono",
        ),
        migrations.AddField(
            model_name="cliente",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="number",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="province",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="surname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="ubigeo",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="verification_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
