# Generated by Django 4.2 on 2026-04-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='document',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
