# Generated by Django 4.2 on 2025-11-13 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_tienda_direccion_alter_tienda_ruc_and_more'),
        ('cliente', '0002_rename_fecha_nacimiento_cliente_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='number',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='surname',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ubigeo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.tienda'),
        ),
    ]
