# Generated by Django 4.2 on 2026-08-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0003_alter_cliente_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
