# Generated by Django 4.2 on 2025-11-13 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_rename_number_cliente_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='verification_code',
        ),
    ]
