# Generated by Django 5.1.2 on 2025-02-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venta",
            old_name="fecha_venta",
            new_name="fecha_hora",
        ),
        migrations.RenameField(
            model_name="venta",
            old_name="descuento",
            new_name="igv",
        ),
        migrations.RenameField(
            model_name="venta",
            old_name="impuestos",
            new_name="total_gravado",
        ),
        migrations.RemoveField(
            model_name="detalleventa",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="factura",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="notas",
        ),
        migrations.AddField(
            model_name="venta",
            name="condicion_venta",
            field=models.CharField(
                choices=[("CONTADO", "Contado"), ("CREDITO", "Crédito")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="direccion_empresa",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="documento_cliente",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="numero",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="qr_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="razon_social",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="ruc_empresa",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="serie",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="tipo_comprobante",
            field=models.CharField(
                choices=[("BOLETA", "Boleta"), ("FACTURA", "Factura")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="url_consulta",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="cantidad",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="precio_unitario",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="venta",
            name="metodo_pago",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="venta",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
