# Generated by Django 4.2 on 2026-04-26 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_tienda_representante_tienda_serie'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieCorrelativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=10)),
                ('correlativo', models.IntegerField(default=0)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.tienda')),
            ],
            options={
                'unique_together': {('tienda', 'serie')},
            },
        ),
    ]
