# Generated by Django 4.2 on 2025-03-15 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('venta', '0002_rename_fecha_venta_venta_fecha_hora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_igv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_igv', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_afectacion_igv', models.CharField(max_length=10)),
                ('total_impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='condicion_venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='direccion_empresa',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='documento_cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='igv',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='qr_url',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ruc_empresa',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total_gravado',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='url_consulta',
        ),
        migrations.AddField(
            model_name='venta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_realizacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.venta'),
        ),
    ]
