# Generated by Django 4.2 on 2026-08-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0002_seriecorrelativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="cliente_json",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
