# Generated by Django 4.2 on 2026-09-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0003_add_cliente_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="tipo_venta",
            field=models.CharField(
                choices=[("PEDIDO", "Pedido"), ("PRESENCIAL", "Presencial")],
                default="PRESENCIAL",
                max_length=20,
            ),
        ),
    ]
