# Generated by Django 4.2 on 2025-03-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_ventaproducto_remove_venta_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='gravado_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='igv_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
