# Generated by Django 4.2 on 2025-03-17 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('venta', '0004_venta_gravado_total_venta_igv_total_venta_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='productos_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto'),
        ),
    ]
