# Generated by Django 4.2 on 2025-04-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_venta_productos_json_alter_ventaproducto_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
