# Generated by Django 4.2 on 2025-08-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_alter_venta_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='nombre_cliente',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_documento_cliente',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_documento_cliente',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
