# Generated by Django 4.2 on 2025-08-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_venta_nombre_cliente_venta_numero_documento_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='ventaproducto',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='venta',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
