# Generated by Django 4.2 on 2025-10-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_alter_venta_options_alter_ventaproducto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='direccion_cliente',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='email_cliente',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='telefono_cliente',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
