# Generated by Django 4.2 on 2025-11-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0009_venta_direccion_cliente_venta_email_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaproducto',
            name='costo_original',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
