# Generated by Django 4.2 on 2025-11-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0010_ventaproducto_costo_original_ventaproducto_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
