# Generated by Django 4.2 on 2026-01-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('razon_social', models.CharField(blank=True, max_length=150, null=True)),
                ('ruc', models.CharField(blank=True, max_length=11, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sol_user', models.CharField(blank=True, max_length=50, null=True)),
                ('sol_password', models.TextField(blank=True, null=True)),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to='tienda_logos/')),
                ('activo', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
