# Generated by Django 5.1.2 on 2025-02-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='activo',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='capacidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
