# Generated by Django 4.2 on 2026-04-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='representante',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='serie',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
