# Generated by Django 4.2 on 2026-04-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_tienda_representante_tienda_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='correlativo_inicial_boleta',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tienda',
            name='correlativo_inicial_factura',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tienda',
            name='correlativo_inicial_nota_credito',
            field=models.IntegerField(default=1),
        ),
    ]
