# Generated by Django 4.2 on 2025-08-18 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0002_alter_tienda_activo_alter_tienda_capacidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiendas_encargadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
