# Generated by Django 4.2 on 2026-05-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_tienda_correlativo_inicial_boleta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='correlativo_inicial_boleta',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='correlativo_inicial_factura',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='correlativo_inicial_nota_credito',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
