# Generated by Django 4.2 on 2025-08-18 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0003_alter_tienda_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='encargado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tienda_encargada', to=settings.AUTH_USER_MODEL),
        ),
    ]
