# Generated by Django 4.2 on 2026-08-27 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tienda", "0004_alter_tienda_correlativo_inicial_boleta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tienda",
            name="propietario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tiendas_propias",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
