# Generated by Django 4.2 on 2025-10-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_tienda_options_tienda_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
