# Generated by Django 4.2 on 2026-08-28 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0005_tienda_propietario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tienda",
            name="sol_password",
        ),
        migrations.RemoveField(
            model_name="tienda",
            name="sol_user",
        ),
    ]
