# Generated by Django 4.2 on 2025-10-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_tienda_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='ruc',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
