# Generated by Django 4.2 on 2026-08-28 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0006_remove_tienda_sol_password_remove_tienda_sol_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tienda",
            name="tienda_padre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sucursales",
                to="tienda.tienda",
            ),
        ),
    ]
