# Generated by Django 4.2 on 2026-01-03 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0007_alter_tienda_direccion_alter_tienda_ruc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='imagen',
        ),
        migrations.AddField(
            model_name='tienda',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='tienda_logos/'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encargado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tienda',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='sol_password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='sol_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddConstraint(
            model_name='tienda',
            constraint=models.UniqueConstraint(fields=('owner', 'nombre'), name='unique_tienda_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='tienda',
            constraint=models.UniqueConstraint(condition=models.Q(('ruc__isnull', False)), fields=('ruc',), name='unique_ruc_no_null'),
        ),
    ]
