# Generated by Django 4.2 on 2026-08-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0007_tienda_tienda_padre"),
    ]

    operations = [
        migrations.AddField(
            model_name="tienda",
            name="banner_img",
            field=models.ImageField(blank=True, null=True, upload_to="tienda_banners/"),
        ),
        migrations.AddField(
            model_name="tienda",
            name="certificado",
            field=models.FileField(
                blank=True, null=True, upload_to="tienda_certificados/"
            ),
        ),
        migrations.AddField(
            model_name="tienda",
            name="design_boleta",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="tienda",
            name="design_factura",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="tienda",
            name="logo_img_dark",
            field=models.ImageField(blank=True, null=True, upload_to="tienda_logos/"),
        ),
    ]
