# Generated by Django 4.2 on 2026-01-03 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_remove_tienda_capacidad_remove_tienda_ciudad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tienda',
            old_name='ruc',
            new_name='ruc_tienda',
        ),
    ]
