# Generated by Django 4.2 on 2026-09-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0008_tienda_banner_img_tienda_certificado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tienda",
            name="cert_clave_privada",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tienda",
            name="cert_clave_publica",
            field=models.TextField(blank=True, null=True),
        ),
    ]
