# Generated by Django 4.2 on 2026-01-03 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_rename_ruc_tienda_ruc_tienda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tienda',
            old_name='ruc_tienda',
            new_name='ruc',
        ),
    ]
