# Generated by Django 4.2 on 2026-09-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0009_tienda_cert_clave_privada_tienda_cert_clave_publica"),
    ]

    operations = [
        migrations.AddField(
            model_name="tienda",
            name="sol_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tienda",
            name="sol_user",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
