# Generated by Django 4.2 on 2026-09-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0010_tienda_sol_password_tienda_sol_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tienda",
            name="tipo_style_boleta_pdf",
            field=models.CharField(blank=True, default="default", max_length=100),
        ),
        migrations.AddField(
            model_name="tienda",
            name="tipo_style_boleta_ticket",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="tienda",
            name="tipo_style_factura_pdf",
            field=models.CharField(blank=True, default="default", max_length=100),
        ),
    ]
