# Generated by Django 4.2 on 2026-01-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_rename_ruc_tienda_tienda_ruc'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tienda',
            name='unique_tienda_por_usuario',
        ),
        migrations.RemoveConstraint(
            model_name='tienda',
            name='unique_ruc_no_null',
        ),
        migrations.AlterField(
            model_name='tienda',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
