# Generated by Django 4.2 on 2026-09-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0011_tienda_tipo_style_boleta_pdf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tienda",
            name="tipo_style_boleta_ticket",
            field=models.CharField(blank=True, default="default", max_length=100),
        ),
    ]
