# Generated by Django 4.2 on 2026-01-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_remove_tienda_unique_tienda_por_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
