# Generated by Django 4.2 on 2026-01-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_alter_tienda_razon_social'),
    ]

    operations = [
       
    ]
