# Generated by Django 4.2 on 2026-09-17 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0012_alter_tienda_tipo_style_boleta_ticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanSuscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_plan", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("limite_boletas", models.PositiveIntegerField(default=0)),
                ("limite_facturas", models.PositiveIntegerField(default=0)),
                ("limite_personal", models.PositiveIntegerField(default=0)),
                (
                    "precio_mensual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("moneda", models.CharField(default="PEN", max_length=3)),
                (
                    "periodo_facturacion",
                    models.CharField(
                        choices=[("mensual", "Mensual"), ("anual", "Anual")],
                        default="mensual",
                        max_length=10,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plan de suscripción",
                "verbose_name_plural": "Planes de suscripción",
                "ordering": ["precio_mensual"],
            },
        ),
        migrations.CreateModel(
            name="UsoMensualTienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.DateField()),
                ("boletas_emitidas", models.PositiveIntegerField(default=0)),
                ("facturas_emitidas", models.PositiveIntegerField(default=0)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "tienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uso_mensual",
                        to="tienda.tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uso mensual de tienda",
                "verbose_name_plural": "Usos mensuales de tiendas",
            },
        ),
        migrations.AddField(
            model_name="tienda",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tiendas",
                to="tienda.plansuscripcion",
            ),
        ),
        migrations.AddConstraint(
            model_name="usomensualtienda",
            constraint=models.UniqueConstraint(
                fields=("tienda", "mes"), name="uq_uso_tienda_mes"
            ),
        ),
    ]
