# Generated by Django 4.2 on 2026-09-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0013_plansuscripcion_usomensualtienda_tienda_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plansuscripcion",
            name="lista_descripcion",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de características del plan (array de strings)",
            ),
        ),
    ]
