# Generated by Django 4.2 on 2026-01-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_remove_tienda_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='owner',
        ),
    ]
