# Generated by Django 4.2 on 2026-01-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_remove_tienda_owner'),
    ]

    operations = [
    ]
