# Generated by Django 4.2 on 2026-09-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0014_plansuscripcion_lista_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="plansuscripcion",
            name="precio_anual",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
