# Generated by Django 4.2 on 2026-01-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_fix_missing_columns'),
        ('tienda', '0016_refactor_tienda_model'),
    ]

    operations = [
    ]
