# Generated by Django 4.2 on 2026-09-19 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0016_tienda_plan_desde"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialPeriodoPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField()),
                ("fin", models.DateTimeField()),
                ("boletas_emitidas", models.PositiveIntegerField(default=0)),
                ("facturas_emitidas", models.PositiveIntegerField(default=0)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="periodos_historial",
                        to="tienda.plansuscripcion",
                    ),
                ),
                (
                    "tienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_periodos",
                        to="tienda.tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de periodo de plan",
                "verbose_name_plural": "Historial de periodos de planes",
                "ordering": ["-inicio"],
            },
        ),
        migrations.AddConstraint(
            model_name="historialperiodoplan",
            constraint=models.UniqueConstraint(
                fields=("tienda", "inicio"), name="uq_historial_tienda_inicio"
            ),
        ),
    ]
