# Generated by Django 4.2 on 2026-01-03 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0017_merge_20260103_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='logo_img',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='sol_password',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='sol_user',
        ),
        migrations.AddField(
            model_name='tienda',
            name='capacidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='encargado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tienda_encargada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tienda',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tiendas/'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='activo',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='ruc',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
