# Generated by Django 4.2 on 2026-09-19 02:34

from django.db import migrations, models


def backfill_limite_productos(apps, schema_editor):
    # Planes existentes: 5x su límite de boletas (mínimo 100) para no
    # bloquear de golpe la creación de productos. Ajustable por endpoint.
    PlanSuscripcion = apps.get_model("tienda", "PlanSuscripcion")
    for plan in PlanSuscripcion.objects.filter(limite_productos=0):
        plan.limite_productos = max(100, (plan.limite_boletas or 0) * 5)
        plan.save(update_fields=["limite_productos"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0017_historialperiodoplan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plansuscripcion",
            name="limite_productos",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_limite_productos, noop),
    ]
