# Generated by Django 4.2 on 2026-09-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0018_plansuscripcion_limite_productos"),
    ]

    operations = [
        migrations.AddField(
            model_name="tienda",
            name="correlativo_inicial_guia_remision",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
