# Generated by Django 4.2 on 2026-01-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0018_remove_tienda_email_remove_tienda_logo_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='imagen',
        ),
        migrations.AddField(
            model_name='tienda',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='tienda_logos/'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='sol_password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='sol_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
