# Generated by Django 4.2 on 2026-09-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0019_tienda_correlativo_inicial_guia_remision"),
    ]

    operations = [
        migrations.AddField(
            model_name="tienda",
            name="api_client_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tienda",
            name="api_client_secret",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
