# Generated by Django 4.2 on 2026-09-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0021_rename_api_client_id_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tienda",
            name="ruc",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
