# Generated by Django 4.2 on 2025-03-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='siglas_nombre_categoria',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
