# Generated by Django 4.2 on 2025-08-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_alter_categoria_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='categoria',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
