# Generated by Django 4.2 on 2025-08-18 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_tienda_activo_alter_tienda_capacidad_and_more'),
        ('categoria', '0002_categoria_siglas_nombre_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='tienda.tienda'),
        ),
    ]
