# Generated by Django 4.2 on 2025-11-15 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0005_alter_categoria_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
    ]
