# Generated by Django 4.2 on 2025-11-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0006_remove_categoria_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='caracteristicas_template',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
